/**
 * Markdown Export Service
 * Generates Markdown-formatted reports from pre-mortem analysis
 * Compatible with GitHub, Notion, and other Markdown renderers
 */

import { DecisionSession } from '@/types/sharedModels';
import { ExportOptions } from '@/components/export/ExportModal';

export async function generateMarkdown(
  session: DecisionSession,
  options: ExportOptions
): Promise<void> {
  let markdown = '';

  // Title and branding
  if (options.includeBranding) {
    markdown += '# 🎯 Pre-Mortem Analysis\n\n';
    markdown += '*Generated by Olumi Pre-Mortem Analysis Tool*\n\n';
    markdown += '---\n\n';
  }

  // Decision Question
  markdown += `## ${session.decision.question}\n\n`;

  // Metadata
  markdown += '**Session Information**\n\n';
  markdown += `- **Created:** ${new Date(session.created_at).toLocaleString()}\n`;
  markdown += `- **Session ID:** \`${session.id}\`\n`;
  markdown += `- **Type:** ${session.type}\n`;
  markdown += `- **Status:** ${session.decision.status}\n\n`;

  markdown += '---\n\n';

  // Context
  if (session.decision.context) {
    markdown += '## 📋 Decision Context\n\n';
    markdown += `${session.decision.context}\n\n`;
    markdown += '---\n\n';
  }

  // Executive Summary
  markdown += '## 📊 Executive Summary\n\n';

  const stats = {
    scenarios: session.premortem?.failure_scenarios.length || 0,
    mitigations: session.premortem?.mitigations.length || 0,
    options: session.decision.options.length,
    factors: session.decision.factors.length,
    stakeholders: session.decision.stakeholders.length,
    confidence: session.premortem?.confidence_level || 'N/A',
  };

  markdown += '| Metric | Value |\n';
  markdown += '|--------|-------|\n';
  markdown += `| Scenarios Identified | ${stats.scenarios} |\n`;
  markdown += `| Mitigations Planned | ${stats.mitigations} |\n`;
  markdown += `| Decision Options | ${stats.options} |\n`;
  markdown += `| Key Factors | ${stats.factors} |\n`;
  markdown += `| Stakeholders | ${stats.stakeholders} |\n`;
  markdown += `| Confidence Level | ${stats.confidence}% |\n\n`;

  markdown += '---\n\n';

  // Decision Options
  if (session.decision.options.length > 0) {
    markdown += '## 🎲 Decision Options\n\n';

    session.decision.options.forEach((option, index) => {
      markdown += `### ${index + 1}. ${option.title}\n\n`;
      markdown += `${option.description}\n\n`;
      markdown += `**Confidence:** ${option.confidence}%`;
      if (option.ai_generated) {
        markdown += ' *(AI-generated)*';
      }
      markdown += '\n\n';
    });

    markdown += '---\n\n';
  }

  // Failure Scenarios
  if (session.premortem && session.premortem.failure_scenarios.length > 0) {
    markdown += '## ⚠️ Potential Failure Scenarios\n\n';

    session.premortem.failure_scenarios.forEach((scenario, index) => {
      markdown += `### ${index + 1}. ${scenario.title}\n\n`;
      markdown += `${scenario.description}\n\n`;

      // Impact and Likelihood badges
      const impactEmoji = {
        catastrophic: '🔴',
        major: '🟠',
        moderate: '🟡',
        minor: '🟢',
      };

      markdown += `**Impact:** ${impactEmoji[scenario.impact] || '⚪'} ${scenario.impact.toUpperCase()}\n\n`;
      markdown += `**Likelihood:** ${scenario.likelihood}%\n\n`;

      // Root Causes
      if (scenario.root_causes && scenario.root_causes.length > 0) {
        markdown += '**Root Causes:**\n\n';
        scenario.root_causes.forEach((cause) => {
          markdown += `- ${cause}\n`;
        });
        markdown += '\n';
      }

      // Early Warning Signs
      if (scenario.early_warning_signs && scenario.early_warning_signs.length > 0) {
        markdown += '**Early Warning Signs:**\n\n';
        scenario.early_warning_signs.forEach((sign) => {
          markdown += `- 🚨 ${sign}\n`;
        });
        markdown += '\n';
      }

      markdown += '---\n\n';
    });
  }

  // Mitigation Strategies
  if (session.premortem && session.premortem.mitigations.length > 0) {
    markdown += '## 🛡️ Mitigation Strategies\n\n';

    // Priority mitigations first
    const priorityMitigations = session.premortem.mitigations.filter((m) => m.priority);
    const otherMitigations = session.premortem.mitigations.filter((m) => !m.priority);

    if (priorityMitigations.length > 0) {
      markdown += '### 🔥 High Priority\n\n';

      priorityMitigations.forEach((mitigation, index) => {
        markdown += `#### ${index + 1}. ${mitigation.strategy}\n\n`;

        // Actions
        if (mitigation.actions && mitigation.actions.length > 0) {
          markdown += '**Action Items:**\n\n';
          mitigation.actions.forEach((action) => {
            markdown += `- [ ] ${action}\n`;
          });
          markdown += '\n';
        }

        // Metadata
        markdown += `**Effort:** ${mitigation.effort.toUpperCase()} | `;
        markdown += `**Effectiveness:** ${mitigation.effectiveness}% | `;
        markdown += `**Timing:** ${mitigation.timing}\n\n`;

        if (mitigation.owner) {
          markdown += `**Owner:** @${mitigation.owner}\n\n`;
        }

        markdown += '---\n\n';
      });
    }

    if (otherMitigations.length > 0) {
      markdown += '### Other Mitigations\n\n';

      otherMitigations.forEach((mitigation, index) => {
        markdown += `#### ${index + 1}. ${mitigation.strategy}\n\n`;

        if (mitigation.actions && mitigation.actions.length > 0) {
          mitigation.actions.forEach((action) => {
            markdown += `- [ ] ${action}\n`;
          });
          markdown += '\n';
        }

        markdown += `**Effort:** ${mitigation.effort} | **Effectiveness:** ${mitigation.effectiveness}%\n\n`;
      });

      markdown += '---\n\n';
    }
  }

  // Key Factors
  if (session.decision.factors.length > 0) {
    markdown += '## 🔑 Key Factors\n\n';

    const factorsByType = session.decision.factors.reduce((acc, factor) => {
      if (!acc[factor.type]) acc[factor.type] = [];
      acc[factor.type].push(factor);
      return acc;
    }, {} as Record<string, typeof session.decision.factors>);

    Object.entries(factorsByType).forEach(([type, factors]) => {
      markdown += `### ${type.charAt(0).toUpperCase() + type.slice(1)}s\n\n`;

      factors.forEach((factor) => {
        const importanceEmoji = {
          critical: '🔴',
          high: '🟠',
          medium: '🟡',
          low: '🟢',
        };

        markdown += `- ${importanceEmoji[factor.importance]} **${factor.name}**`;
        if (factor.description) {
          markdown += `: ${factor.description}`;
        }
        markdown += '\n';
      });

      markdown += '\n';
    });

    markdown += '---\n\n';
  }

  // Stakeholders
  if (session.decision.stakeholders.length > 0) {
    markdown += '## 👥 Stakeholders\n\n';

    markdown += '| Name | Role | Influence |\n';
    markdown += '|------|------|----------|\n';

    session.decision.stakeholders.forEach((stakeholder) => {
      markdown += `| ${stakeholder.name} | ${stakeholder.role} | ${stakeholder.influence.toUpperCase()} |\n`;
    });

    markdown += '\n---\n\n';
  }

  // Conversation History
  if (options.includeConversation && session.conversation.length > 0) {
    markdown += '## 💬 Conversation History\n\n';

    session.conversation.forEach((message) => {
      const role = message.role === 'user' ? '**You**' : '**Olumi**';
      const timestamp = new Date(message.timestamp).toLocaleTimeString();

      markdown += `### ${role} *at ${timestamp}*\n\n`;
      markdown += `${message.content}\n\n`;

      if (message.reasoning) {
        markdown += `> *Reasoning: ${message.reasoning}*\n\n`;
      }
    });

    markdown += '---\n\n';
  }

  // Diagnostics
  if (options.includeDiagnostics && session.diagnostics) {
    markdown += '## 🔍 Diagnostics\n\n';

    markdown += '**Performance Metrics:**\n\n';
    markdown += `- Total Processing Time: ${(session.diagnostics.totalProcessingTimeMs / 1000).toFixed(2)}s\n`;
    markdown += `- API Calls: ${session.diagnostics.apiCalls.length}\n`;
    markdown += `- Status: ${session.diagnostics.degraded ? '⚠️ Degraded' : '✅ Healthy'}\n\n`;

    if (session.diagnostics.degradedReason) {
      markdown += `**Degraded Reason:** ${session.diagnostics.degradedReason}\n\n`;
    }

    if (session.diagnostics.warnings && session.diagnostics.warnings.length > 0) {
      markdown += '**Warnings:**\n\n';
      session.diagnostics.warnings.forEach((warning) => {
        markdown += `- ⚠️ ${warning}\n`;
      });
      markdown += '\n';
    }

    markdown += '**API Call Details:**\n\n';
    markdown += '| Step | Model | Duration | Status |\n';
    markdown += '|------|-------|----------|--------|\n';

    session.diagnostics.apiCalls.forEach((call) => {
      const statusIcon = call.status === 'success' ? '✅' : '❌';
      markdown += `| ${call.step} | ${call.model} | ${(call.durationMs / 1000).toFixed(2)}s | ${statusIcon} ${call.status} |\n`;
    });

    markdown += '\n---\n\n';
  }

  // Footer
  if (options.includeBranding) {
    markdown += '\n\n---\n\n';
    markdown += '*Generated by [Olumi Pre-Mortem Analysis Tool](https://olumi.ai)*\n';
  }

  // Download the file
  const fileName = options.fileName || getDefaultFileName(session);
  downloadMarkdown(markdown, `${fileName}.md`);
}

function getDefaultFileName(session: DecisionSession): string {
  const timestamp = new Date().toISOString().split('T')[0];
  const sanitizedQuestion = session.decision.question
    .replace(/[^a-z0-9]/gi, '-')
    .toLowerCase()
    .substring(0, 50);
  return `premortem-${sanitizedQuestion}-${timestamp}`;
}

function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
